admissions/urls.py
from django.conf.urls import url, include

from . import views

class api:
  urlpatterns = [
    url(r'^states/$', views.api_student_states, name='api_all_student_states'),
    url(r'^(?P<college_code>[a-z]{3})/states/$', views.api_student_states, name='api_student_states'),
    url(r'^collegelist/$', views.api_get_colleges),
  ]

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^api/', include(api)),
  url(r'^apps/all/$', views.all_applicants, name='all_applicants'),
  url(r'^apps/active/$', views.active_applicants, name='active_applicants'),
  url(r'^apps/(?P<college_code>[a-z]{3})/$', views.college_applicants, name='college_applicants'),
  url(r'^colleges/$', views.college_list, name='colleges'),
  url(r'^college/(?P<college_code>[a-z]{3})/$', views.view_or_edit_college, name="edit_college"),
  url(r'^shortlist/$', views.view_shortlist_report, name="view_shortlist"),
  url(r'^decisions/(?P<college_code>[a-z]{3})/$', views.view_decisions_college, name="view_decisions_college"),
  url(r'^teams/(?P<college_code>[a-z]{3})/$', views.view_or_edit_teams, name="edit_teams"),
  url(r'^schedule/(?P<college_code>[a-z]{3})/$', views.view_schedule, name="view_schedule"),
  url(r'^schedule/(?P<team_pk>[0-9]+)/$', views.view_or_edit_schedule, name="edit_schedule"),
  url(r'^schedule/t/(?P<team_pk>[0-9]+)/$', views.view_team_schedule, name="view_team_schedule"),
  url(r'^schedule/c/(?P<candidate_pk>[0-9]+)/$', views.view_candidate_schedule, name="view_candidate_schedule"),
  url(r'^schedule/notes/$', views.notes_schedule, name='notes_schedule'),
  url(r'^notes/$', views.notes, name='notes'),
]

phyad/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    #url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admissions/', include('admissions.urls', namespace='admissions')),
    url(r'^webauth/', include('webauth.urls')),
    url(r'^accounts/login/', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout', kwargs={'template_name':'registration/logout.html'}, name='phyad_logout'),
    url(r'^consent/', lambda req:redirect('admissions:index')),
    url(r'^$', lambda req:redirect('admissions:index')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admissions/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

import datetime

from admissions.models import College, InterviewTeam

class CollegeForm(ModelForm):
  class Meta:
    model = College
    exclude = [ 'name', 'adss_code', 'key', ]

InterviewTeamFormset = inlineformset_factory(College, InterviewTeam, 
    fields = [ 'names', 'location', 'notes', ],
    can_delete=True, extra=1)


admissions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponse
from admissions.models import *
from admissions.forms import *
import json
import logging
import datetime
from array import array

# Create your views here.

# Used for logging events
logger =  logging.getLogger(__name__)
default_weights = Weights.objects.last()
logger.info("default weights {0} {1} {2} {3}".format(
            default_weights.pat_maths,
            default_weights.pat_physics,
            default_weights.interview1,
            default_weights.interview2))

def get_colleges_for_user(u):
    colleges = College.objects.all()
    if u.is_superuser or u.is_staff:
        return colleges
    return [c for g in u.groups.all() for c in colleges if g.name == c.adss_code]

def get_college_codes_for_user(u):
    if u.is_superuser or u.is_staff:
        return ['ALL']
    colleges = College.objects.all()
    clist = []
    for g in u.groups.all():
        for c in colleges:
            if g.name == c.adss_code:
                clist.append(c.adss_code)
    return clist

def get_college_keys_for_user(u):
    colleges = College.objects.all()
    clist = []
    if u.is_superuser or u.is_staff:
        for c in colleges:
            clist.append({ 'c':c.adss_code, 'k':c.key })
    else:
        for c in colleges:
            for g in u.groups.all():
                if g.name == c.adss_code:
                    clist.append({ 'c':g.name, 'k':c.key })
    return clist

#---------------------------------------------------------------
# front pages
#---------------------------------------------------------------

@login_required
def index(request):
    return render(request, 'admissions/consent.html', {});

@login_required
def notes(request):
    return render(request, 'admissions/notes.html', {});

@login_required
def college_list(request):
    state = OverallState.objects.current()
    colleges = College.objects.all()
    collegedata = {}
    for c in colleges:
        cdata = {
            'np': c.total_places - c.physphil_places,
            'npp': c.physphil_places,
            'op': 0,
            'opp': 0,
            'fp': 0,
            'fpp': 0,
            }
        collegedata[c.adss_code] = cdata
    if state == OverallState.FINAL:
        offers = Offer.objects.filter(final=True)
    else:
        offers = Offer.objects.all()
    offers = Offer.objects.all()
    for o in offers:
        c = o.college
        if c.adss_code != None and c.adss_code != '' and not o.deferred_entry:
            offerclass = 'o'
            if hasattr(o,'promoted') and o.promoted:
              offerclass = 'f'
            if o.course_type == Candidate.COURSE_PHYSPHIL_ONLY:
                offertype = 'pp'
            else:
                offertype = 'p'
            collegedata[c.adss_code][offerclass+offertype] = \
                    collegedata[c.adss_code][offerclass+offertype] + 1
    template_values = {
        'colleges': colleges,
        'data': json.dumps(collegedata),
        'state': state,
        #'year': present_interview_year(),
        }
    return render(request, 'admissions/colleges.html', template_values);

#---------------------------------------------------------------
# main browsing pages
#---------------------------------------------------------------

@login_required
def all_applicants(request):
  college = { "name": "All including W/D", "adss_code": "APP" }
  return applicant(request, college)

@login_required
def active_applicants(request):
  college = { "name": "All active", "adss_code": "ALL" }
  return applicant(request, college)

@login_required
def college_applicants(request, college_code):
  college = get_object_or_404(College, adss_code=college_code.upper())
  return applicant(request, college)

def applicant(request, college_spec):
  state = OverallState.objects.current()
  ranking_phase = OverallState.objects.current_ranking_phase()
  template_values = {
    'path':request.path,
    'user_colleges':json.dumps(get_college_codes_for_user(request.user)),
    'can_edit':request.user.is_superuser,
    'college':college_spec,
    'present_interview_year':present_interview_year(),
    'state':state,
    'ranking_phase':ranking_phase,
    'state_longlist':(state in [OverallState.LONGLIST,
                                OverallState.DEVELOPMENT]),
    'state_enter_interview_marks':(state in [OverallState.SHORTLIST,
                                             OverallState.DEVELOPMENT]),
    'state_enter_offers':(state in [OverallState.OFFERS,
                                    OverallState.DEVELOPMENT]),
    'weights':default_weights,
    }
  if state == OverallState.SHORTLIST:
    template_values['college_key_list'] = json.dumps(get_college_keys_for_user(request.user))
  return render(request, 'admissions/applicants.html', template_values)

#---------------------------------------------------------------
# college
#---------------------------------------------------------------

@login_required
def view_or_edit_college(request, college_code, return_to=None):
  if not return_to:
    return_to = request.GET.get('next', reverse('admissions:colleges'))
  c = get_object_or_404(College, adss_code=college_code.upper())
  if c in get_colleges_for_user(request.user):
    return edit_college(request, c, return_to)
  return view_college(request, c, return_to)

def view_college(request, college, return_to='admissions:colleges'):
  tutors = User.objects.filter(groups__name__exact=college.adss_code)
  tutornames = ', '.join([ t.last_name for t in tutors ])
  tutormail = ','.join([ t.email for t in tutors ])
  template_values = {
      'return_to': return_to,
      'college': college,
      'tutormail': tutormail,
      'tutornames': tutornames,
      }
  return render(request, 'admissions/view_college.html', template_values)
  #return render_to_response('admissions/view_college.html', template_values)

def edit_college(request, college, return_to='admissions:colleges'):
  if request.method == 'POST':
    if college not in get_colleges_for_user(request.user):
      return redirect('admissions:colleges') # not authorized
    college_form = CollegeForm(request.POST, instance=college)
    if college_form.is_valid():
      college_form.save()
    kwargs = {
        'college_code': college.adss_code,
        #'return_to': return_to,
        }
    all_valid = college_form.is_valid()
    if all_valid:
      #return redirect('admissions:edit_college', **kwargs)
      return redirect('admissions:colleges')
  else:
    college_form = CollegeForm(instance=college)

  tutors = User.objects.filter(groups__name__exact=college.adss_code)
  tutornames = ', '.join([ t.last_name for t in tutors ])
  tutormail = ','.join([ t.email for t in tutors ])
  template_values = {
      'return_to': return_to,
      'college': college,
      'tutormail': tutormail,
      'tutornames': tutornames,
      'college_form': college_form,
      }
  return render(request, 'admissions/edit_college.html', template_values)

#---------------------------------------------------------------
# shortlist report
#---------------------------------------------------------------

@login_required
def view_shortlist_report(request, return_to='admissions:colleges'):
  total_places = 0
  for c in College.objects.all():
    total_places = total_places + c.total_places
  shortlist_target = total_places * default_weights.shortlist_per_place
  if shortlist_target > default_weights.shortlist_max:
    shortlist_target = default_weights.shortlist_max
  logger.info("Shortlist target {}".format(shortlist_target))
  marks = array('l')
  rescues = array('l')
  for i in range(0, 101):
    marks.append(0)
  for i in range(0, 101):
    rescues.append(0)
  for s in Candidate.objects.all():
    pt = int(s.pat_physics + s.pat_maths)
    marks[pt] = marks[pt] + 1
    if (s.rescued or s.reserved):
      rescues[pt] = rescues[pt] + 1
  scores = []
  for i in range(0, 101):
    scores.append({ 'index':i, 'pat':marks[i], 'rescues':rescues[i] })
  template_values = {
    'return_to': return_to,
    'scores': scores,
    'shortlist_target': shortlist_target,
    }
  return render(request, 'admissions/view_shortlist_report.html', template_values)

#---------------------------------------------------------------
# decisions reports
#---------------------------------------------------------------

@login_required
def view_decisions_college(request, college_code):
  c = get_object_or_404(College, adss_code=college_code.upper())
  cands = Candidate.objects.filter(college1=c).select_related('info').order_by('info__surname','info__forenames')
  summoned = cands.filter(state=Candidate.STATE_SUMMONED)
  desummoned = cands.filter(state=Candidate.STATE_DESUMMONED)
  withdrawn = cands.filter(state=Candidate.STATE_WITHDRAWN)
  offers = Offer.objects.filter(college=c, final=True)
  template_values = {
    'college': c,
    'summoned': summoned,
    'desummoned': desummoned,
    'withdrawn': withdrawn,
    'offers': offers,
  }
  return render(request, 'admissions/view_decisions_college.html', template_values)

#---------------------------------------------------------------
# interview teams
#---------------------------------------------------------------

@login_required
def view_or_edit_teams(request, college_code, return_to=None):
  if not return_to:
    return_to = request.GET.get('next', reverse('admissions:colleges'))
  c = get_object_or_404(College, adss_code=college_code.upper())
  if c in get_colleges_for_user(request.user):
    return edit_teams(request, c, return_to)
  return view_teams(request, c, return_to)

def view_teams(request, college, return_to='admissions:colleges'):
  teams = college.interview_team.all()
  tutors = User.objects.filter(groups__name__exact=college.adss_code)

admissions/templates/admissions/colleges.html
{% extends "base.html" %}
{% load url from future %}
{% load staticfiles %}
{% block title %}
Admissions database - college list{% if year %} for {{ year }}{% endif %}
{% endblock %}
{% block head %}
<script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
<style>
table { font-size: 13px;
}
th {
  font-weight: bold;
  padding-left: 3em;
  padding-right: 3em;
}
.notice { font-weight: bold; color: red }
</style>
{% endblock %}
{% block content %}
<h2>Colleges {% if year %}(historical data for {{ year }} interview cycle){% else %}- present interview cycle{% endif %}</h2>

<!--
<p class="notice">
Please complete rescuing/ring-fencing (&quot;saving&quot) by 8pm on Saturday 22 November 2014.
</p>
-->

<p><a href="{% url 'admissions:active_applicants'|lower %}">Active applicant list for all colleges</a></p>
<p><a href="{% url 'admissions:all_applicants'|lower %}">Complete applicant list for all colleges</a></p>

<p>
The above data files contain roughly 4MB of data.
The following smaller applicant lists are provided for those with lower
bandwidth connections or old browsers, such as IE9.
</p>

<p>Counts below are for the next academic year, and
do not include deferred offers.</p>

<table id="clist">
<tr><th>Applicants</th>
<!--<th>Interview</th><th>Schedule</th>-->
<th>Places</th>
<th>Offers made</th>
<th>Flags</th>
<th>Interviews</th>
<th>Decisions</th>
</tr>
<tr><th></th>
<!--<th>teams</th><th>(do not use yet)</th>-->
<th>(incl PhysPhil)</th>
<th>(incl PhysPhil)</th>
<th>(incl PhysPhil)</th>
<th></th>
<th></th>
</tr>
{% for college in colleges %}
<tr>
  <td><a href="{% url 'admissions:college_applicants' college_code=college.adss_code|lower %}">{{ college.name }}</a></td>
  <td class='cplaces'><a href="{% url 'admissions:edit_college' college_code=college.adss_code|lower %}">{{ college.total_places }}({{ college.physphil_places }})</a></td>
  <td id='offers-{{ college.adss_code }}'></td>
  <td id='flags-{{ college.adss_code }}'></td>
  <td>
    <a href="{% url 'admissions:edit_teams' college_code=college.adss_code|lower %}">Teams</a>
    {% if state == 'S' or state == 'D' %}
    <a href="{% url 'admissions:view_schedule' college_code=college.adss_code|lower %}">Schedule</a>
    {% endif %}
  </td>
  <td><a href="{% url 'admissions:view_decisions_college' college_code=college.adss_code|lower %}">{{ college.adss_code }}</a></td>
</tr>
{% endfor %}
</table>

<p><b>Places:</b>
<table id="places">
<tr><th></th><th>Projected</th><th>Offers made</th><th>Flags</th></tr>
<tr><th></th><th></th><th>(not unique)</th><th>(not unique)</th></tr>
<tr><th align='right'>Physics:</th>
    <td align='center' id="physplaces"></td>
    <td align='center' id="physoffers"></td>
    <td align='center' id="physflags"></td></tr>
<tr><th align='right'>PhysPhil:</th>
    <td align='center' id="physphilplaces"></td>
    <td align='center' id="physphiloffers"></td>
    <td align='center' id="physphilflags"></td></tr>
<tr><th align='right'>Total:</th>
    <td align='center' id="totalplaces"></td>
    <td align='center' id="totaloffers"></td>
    <td align='center' id="totalflags"></td>
</table>
</p>

<p>
<a href="{% url 'admissions:view_shortlist' %}">Shortlist report</a>
</p>

{% if year %}<p><a href="{% url 'admissions:colleges' %}">Back to viewing present data</a></p>{% endif %}
{% endblock %}

{% block scripts %}
<script>
var data_string = "{{ data }}";
var data_cleaned = data_string.replace(/&quot;/g,'"');
var data = JSON.parse(data_cleaned);

$(document).ready(function() {
  var ot = 0;
  var opp = 0;
  var ft = 0;
  var fpp = 0;
  $.each(data, function(k,v) {
    var ccode = k;
    var total = v.op + v.opp;
    var pp = v.opp;
    var s = "" + total.toString() + "(" + pp.toString() + ")";
    ot += total;
    opp += pp;
    $('#offers-'+ccode).html(s);
    //console.log('offers-' + ccode + ':  ' + s);
    total = v.fp + v.fpp;
    pp = v.fpp;
    ft += total;
    fpp += pp;
    s = "" + total.toString() + "(" + pp.toString() + ")";
    $('#flags-'+ccode).html(s);
  });

  var nt = 0;
  var npp = 0;
  $('.cplaces').each(function(i,e) {
    var s = $(this).text();
    //console.log('i = ' + i + ' s = ' + s);
    var n = s.match(/[0-9]+/g);
    nt += parseInt(n[0]);
    npp += parseInt(n[1]);
  });
  var np = nt - npp;
  var op = ot - opp;
  var fp = ft - fpp;
  $('#physplaces').html(np.toString());
  $('#physphilplaces').html(npp.toString());
  $('#totalplaces').html(nt.toString());
  $('#physoffers').html(op.toString());
  $('#physphiloffers').html(opp.toString());
  $('#totaloffers').html(ot.toString());
  $('#physflags').html(fp.toString());
  $('#physphilflags').html(fpp.toString());
  $('#totalflags').html(ft.toString());
});
</script>
{% endblock %}

admissions/templates/admissions/edit_teams.html
{% extends "base.html" %}
{% load url from future %}
{% block title %}
Admissions database - edit interview teams {{ college.name }} ({{ college.adss_code }})
{% endblock %}
{% block content %}
<h2>Interview teams for {{ college.name }} ({{ college.adss_code }})</h2>

<p>To add a team, fill out blank form and hit &quot;Update&quot;.
To add another team, return to this form from the college list page.
To delete a team, check the &quot;Delete&quot; box and then &quot;Update&quot;.
</p>

<form method="POST">
{% csrf_token %}
{% for form in teams %}
  <p>
  <table border='0'>
  {% for hidden in form.hidden_fields %}
  {{ hidden }}
  {% endfor %}
  {% for field in form.visible_fields %}
  <tr><td class="fieldWrapper" align="right" title="{{ field.help_text }}">{{ field.label_tag }}
          {{ field.errors }}
      </td>
      <td class="fieldWrapper" align="left">{{ field }}</td></tr>
  {% endfor %}
  </table>
  </p>
  <hr>
{% endfor %}
  <input type="hidden" name="next" value="{{ return_to }}" />
  <input type="submit" value="Update" />
{{ teams.management_form }}
</form>
{% endblock %}

admissions/templates/admissions/index.html
{% extends "base.html" %}
{% load url from future %}
{% block content %}
<p><a href="{% url 'admissions:colleges' %}">College list</a></p>
{% endblock %}

admissions/templates/admissions/view_candidate_schedule.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
{% load url from future %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
Interview Schedule:  {{ info.surname }}, {{ info.forenames }}
</title>
</head>
<body>

<h2>Interview schedule for {{ info.surname }}, {{ info.forenames }} ({{ candidate.ucas_id }})</h2>

<p>
<ul>
{% for slot in slots %}
<li> <b>{{ slot.time }}</b>
  <ul>
  <li> {{ slot.team.college.name }}  ({{ slot.team.location }})
  <li> Subject:  {{ slot.subject }}
  <li> Interviewers:  {{ slot.team.names }}<br>
       {{ slot.team.notes }}
  </ul>
{% empty %}
<li> No interviews defined
{% endfor %}
</ul>
</p>

</body>
</html>

admissions/templates/admissions/view_schedule.html
{% extends "base.html" %}
{% load url from future %}
{% load staticfiles %}
{% block title %}
Admissions database - {{ college.name }} schedule
{% endblock %}
{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href='{% static "js/DataTables-1.10.2/media/css/jquery.dataTables.min.css" %}'>
<link rel="stylesheet" href='{% static "js/DataTables-1.10.2/extensions/ColVis/css/dataTables.colVis.min.css" %}'>
<link rel="stylesheet" href='{% static "js/DataTables-1.10.2/extensions/TableTools/css/dataTables.tableTools.min.css" %}'>
<script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
<script src='{% static "js/DataTables-1.10.2/media/js/jquery.dataTables.min.js" %}'></script>
<script src='{% static "js/DataTables-1.10.2/extensions/ColVis/js/dataTables.colVis.min.js" %}'></script>
<script src='{% static "js/DataTables-1.10.2/extensions/TableTools/js/dataTables.tableTools.min.js" %}'></script>
<script src='{% static "js/jquery-cookie-1.4.1/jquery.cookie.js" %}'></script>
<style>

.clash { color: red }

</style>
{% endblock %}
{% block content %}
<h2>Interviews for {{ college.name }} ({{ college.adss_code }})</h2>

<p>
<table id="slots" class="display compact" cellspacing="0" cellpadding="0" width="100%">
<thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    {% for team in teams %}
    <th colspan="4" valign="top" align="left">
      <a href="{% url 'admissions:view_team_schedule' team_pk=team.pk %}" target='_blank'>{{ team.names }}</a>
      {% if allow_edit %}
      <a href="{% url 'admissions:edit_schedule' team_pk=team.pk %}">(Edit)</a>
      {% endif %}
    </th>
    {% endfor %}
    <th></th>
  </tr>
  <tr>
    <th>Candidate</th>
    <th>Order</th>
    <th>Col1</th>
    {% for team in teams %}
    <th>Subject</th>
    <th>Mode</th>
    <th>Start</th>
    <th>End</th>
    {% endfor %}
    <th>Other interviews</th>
  </tr>
</thead>
<tfoot>
  <tr>
    <th>Candidate</th>
    <th>Order</th>
    <th>Col1</th>
    {% for team in teams %}
    <th>Subject</th>
    <th>Mode</th>
    <th>Start</th>
    <th>End</th>
    {% endfor %}
    <th>Other interviews</th>
  </tr>
</tfoot>
</table>
</p>
{% endblock %}

{% block scripts %}
<script>
var teams = [];
var tslots = {};
{% for team in teams %}
teams.push({{ team.pk }});
tslots[{{ team.pk }}] = [];
{% endfor %}
var teamspk2i = {};
$.each(teams, function(index, value) {
  teamspk2i[value] = index;
});

var students = {};
{% for student in students %}
students[{{ student.pk }}] = {
  "n": "{{ student.info.surname }}, {{ student.info.forenames }}",
  "c": "{{ student.college1.adss_code }}",
  "s": []
};
{% endfor %}

{% for slot in slots %}
students[{{ slot.candidate.pk }}]["s"].push({
    "tpk": {{ slot.team.pk }},
    "tcol": "{{ slot.team.college.adss_code }}",
    "subject": "{{ slot.subject }}",
    "mode": "{{ slot.mode }}",
    "datetime": {{ slot.time|date:"U" }},
    "duration": {{ slot.length }},
});
{% endfor %}

var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

function twoDigit(n) {
  var s = (n < 10 ? "0" : "");
  return s + n;
}

function formatDate(d) {
  return twoDigit(d.getDate()) + " " + months[d.getMonth()];
}

function formatTime(d) {
  //return d.toLocaleTimeString();
  return twoDigit(d.getHours()) + ":" + twoDigit(d.getMinutes());
}

function is_clash(a, b, pad) {
  var t0 = b.datetime - pad * 60;
  var t1 = b.datetime + (b.duration + pad) * 60;
  var u0 = a.datetime;
  var u1 = a.datetime + a.duration * 60;
  if (u1 <= t0) return false;
  if (u0 >= t1) return false;
  return true;
}

function any_clash(bs, pad) {
  for (var i = 0; i < bs.length; ++i) {
    for (var j = i + 1; j < bs.length; ++j) {
      if (is_clash(bs[i], bs[j], pad)) return true;
    }
  }
  return false;
}

// detect any clashes within a team schedule (only direct overlaps)
$.each(students, function(pk, v) {
  if (v.s.tpk in teams) {
    tslots[v.s.tpk].push({
      "datetime": v.s.datetime,
      "duration": v.s.duration
    });
  }
});
var tclash = {};
$.each(tslots, function(pk, v) {
  tclash[pk] = any_clash(v, 0);
});

var dataset = [];
$.each(students, function(pk, v) {
  var fields = [];
  var last = 3+4*teams.length; // last element of array of length 2+5*j
  for (var i = last; i > 0; --i) fields[i] = ""; // pre-initialize array
  var nm = "<a href=\"{% url 'admissions:view_candidate_schedule' candidate_pk=999999 %}\" target='_blank'>" + v.n + "</a>";
  fields[0] = nm.replace(/999999/g,"" + pk);
  fields[1] = (v.c == "{{ college.adss_code }}") ? 1 : 2;
  var prefix = "<span class='clash'>";
  var postfix = "</span>";
  var rowclash = any_clash(v.s, 20); // 20min padding
  fields[2] = rowclash ? prefix + v.c + postfix : v.c;
  $.each(v.s, function(i, u) {
    var tpk = u.tpk;
    for (var j = 0; j < teams.length; ++j) {
      if (teams[j] == tpk) {
        var a = new Date(u.datetime * 1000);
        var b = new Date((u.datetime + u.duration*60) * 1000);
        //console.log("start " + a + " end " + b);
        var jj = j * 4 + 2;
        var spre = (rowclash || tclash[tpk]) ? prefix : "";
        var spost = (rowclash || tclash[tpk]) ? postfix : "";
        fields[++jj] = spre + u.subject + spost;
        fields[++jj] = spre + u.mode + spost;
        fields[++jj] = spre + formatDate(a) + " " + formatTime(a) + spost;
        fields[++jj] = spre + formatTime(b) + spost;
        return true;
      }
    }
    // not one of the college teams, so append to other interviews
    if (fields[last].length > 0) fields[last] += ', ';
    var a = new Date(u.datetime * 1000);
    fields[last] += (u.mode != "local" ? "("+u.mode+") " : "") +
                     u.tcol + " " + formatDate(a) + " " + formatTime(a);
  });
  dataset.push(fields);
});

//console.log(dataset);

$(document).ready(function() {

  var spec = {
    dom: 'TC<"clear">lfrtip', // add an R to use colReorder
    data: dataset,
    columns: [
      { name: "name" },
      { name: "order" },
      { name: "college1" },
    ],
    "pageLength": 50,
    "order": [ [ 1, "asc" ], [ 0, "asc" ] ],
    "statesave": true,
    "tableTools": {
      "aButtons": [
        "copy",
        "csv",
        {
          "sExtends": "pdf",
          "sPdfOrientation": "portrait"
        },
        "print"
      ],
      "sSwfPath": '{% static "js/DataTables-1.10.2/extensions/TableTools/swf/copy_csv_xls_pdf.swf" %}'
    }
  };
  for (var i = 0; i < teams.length; ++i) {
    spec.columns.push({ name: "subject" + i });
    spec.columns.push({ name: "mode" + i });
    spec.columns.push({ name: "time" + i });
    spec.columns.push({ name: "end" + i });
  }
  spec.columns.push({ name: "other" });
  //console.log(spec);
  $('#slots').DataTable(spec);

});

</script>
{% endblock %}